
package wspub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "demandesService", targetNamespace = "http://wsPub/", wsdlLocation = "http://localhost:1212/ws?wsdl")
public class DemandesService
    extends Service
{

    private final static URL DEMANDESSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMANDESSERVICE_EXCEPTION;
    private final static QName DEMANDESSERVICE_QNAME = new QName("http://wsPub/", "demandesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1212/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMANDESSERVICE_WSDL_LOCATION = url;
        DEMANDESSERVICE_EXCEPTION = e;
    }

    public DemandesService() {
        super(__getWsdlLocation(), DEMANDESSERVICE_QNAME);
    }

    public DemandesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMANDESSERVICE_QNAME, features);
    }

    public DemandesService(URL wsdlLocation) {
        super(wsdlLocation, DEMANDESSERVICE_QNAME);
    }

    public DemandesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMANDESSERVICE_QNAME, features);
    }

    public DemandesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemandesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Demandes
     */
    @WebEndpoint(name = "demandesPort")
    public Demandes getDemandesPort() {
        return super.getPort(new QName("http://wsPub/", "demandesPort"), Demandes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Demandes
     */
    @WebEndpoint(name = "demandesPort")
    public Demandes getDemandesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsPub/", "demandesPort"), Demandes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMANDESSERVICE_EXCEPTION!= null) {
            throw DEMANDESSERVICE_EXCEPTION;
        }
        return DEMANDESSERVICE_WSDL_LOCATION;
    }

}
