
package wspub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "demandes", targetNamespace = "http://wsPub/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demandes {


    /**
     * 
     * @return
     *     returns java.util.List<wspub.Livre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficheAll", targetNamespace = "http://wsPub/", className = "wspub.AfficheAll")
    @ResponseWrapper(localName = "afficheAllResponse", targetNamespace = "http://wsPub/", className = "wspub.AfficheAllResponse")
    @Action(input = "http://wsPub/demandes/afficheAllRequest", output = "http://wsPub/demandes/afficheAllResponse")
    public List<Livre> afficheAll();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectDernierPanier", targetNamespace = "http://wsPub/", className = "wspub.SelectDernierPanier")
    @ResponseWrapper(localName = "selectDernierPanierResponse", targetNamespace = "http://wsPub/", className = "wspub.SelectDernierPanierResponse")
    @Action(input = "http://wsPub/demandes/selectDernierPanierRequest", output = "http://wsPub/demandes/selectDernierPanierResponse")
    public int selectDernierPanier();

    /**
     * 
     * @param l
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editLivre", targetNamespace = "http://wsPub/", className = "wspub.EditLivre")
    @ResponseWrapper(localName = "editLivreResponse", targetNamespace = "http://wsPub/", className = "wspub.EditLivreResponse")
    @Action(input = "http://wsPub/demandes/editLivreRequest", output = "http://wsPub/demandes/editLivreResponse")
    public int editLivre(
        @WebParam(name = "l", targetNamespace = "")
        Livre l);

    /**
     * 
     * @param m
     * @return
     *     returns java.util.List<wspub.Livre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRec", targetNamespace = "http://wsPub/", className = "wspub.GetRec")
    @ResponseWrapper(localName = "getRecResponse", targetNamespace = "http://wsPub/", className = "wspub.GetRecResponse")
    @Action(input = "http://wsPub/demandes/getRecRequest", output = "http://wsPub/demandes/getRecResponse")
    public List<Livre> getRec(
        @WebParam(name = "M", targetNamespace = "")
        String m);

    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns wspub.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recClient", targetNamespace = "http://wsPub/", className = "wspub.RecClient")
    @ResponseWrapper(localName = "recClientResponse", targetNamespace = "http://wsPub/", className = "wspub.RecClientResponse")
    @Action(input = "http://wsPub/demandes/recClientRequest", output = "http://wsPub/demandes/recClientResponse")
    public Client recClient(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param id
     * @return
     *     returns wspub.Livre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectLivreId", targetNamespace = "http://wsPub/", className = "wspub.SelectLivreId")
    @ResponseWrapper(localName = "selectLivreIdResponse", targetNamespace = "http://wsPub/", className = "wspub.SelectLivreIdResponse")
    @Action(input = "http://wsPub/demandes/selectLivreIdRequest", output = "http://wsPub/demandes/selectLivreIdResponse")
    public Livre selectLivreId(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param l
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterLivre", targetNamespace = "http://wsPub/", className = "wspub.AjouterLivre")
    @ResponseWrapper(localName = "ajouterLivreResponse", targetNamespace = "http://wsPub/", className = "wspub.AjouterLivreResponse")
    @Action(input = "http://wsPub/demandes/ajouterLivreRequest", output = "http://wsPub/demandes/ajouterLivreResponse")
    public int ajouterLivre(
        @WebParam(name = "l", targetNamespace = "")
        Livre l);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerLivre", targetNamespace = "http://wsPub/", className = "wspub.SupprimerLivre")
    @ResponseWrapper(localName = "supprimerLivreResponse", targetNamespace = "http://wsPub/", className = "wspub.SupprimerLivreResponse")
    @Action(input = "http://wsPub/demandes/supprimerLivreRequest", output = "http://wsPub/demandes/supprimerLivreResponse")
    public void supprimerLivre(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param idl
     * @param qte
     * @param idc
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterP", targetNamespace = "http://wsPub/", className = "wspub.AjouterP")
    @ResponseWrapper(localName = "ajouterPResponse", targetNamespace = "http://wsPub/", className = "wspub.AjouterPResponse")
    @Action(input = "http://wsPub/demandes/ajouterPRequest", output = "http://wsPub/demandes/ajouterPResponse")
    public int ajouterP(
        @WebParam(name = "idc", targetNamespace = "")
        int idc,
        @WebParam(name = "idl", targetNamespace = "")
        int idl,
        @WebParam(name = "qte", targetNamespace = "")
        int qte);

    /**
     * 
     * @param c
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ClientNewCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ClientNewCompte", targetNamespace = "http://wsPub/", className = "wspub.ClientNewCompte")
    @ResponseWrapper(localName = "ClientNewCompteResponse", targetNamespace = "http://wsPub/", className = "wspub.ClientNewCompteResponse")
    @Action(input = "http://wsPub/demandes/ClientNewCompteRequest", output = "http://wsPub/demandes/ClientNewCompteResponse")
    public boolean clientNewCompte(
        @WebParam(name = "c", targetNamespace = "")
        Client c);

    /**
     * 
     * @param email
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifEmail", targetNamespace = "http://wsPub/", className = "wspub.VerifEmail")
    @ResponseWrapper(localName = "verifEmailResponse", targetNamespace = "http://wsPub/", className = "wspub.VerifEmailResponse")
    @Action(input = "http://wsPub/demandes/verifEmailRequest", output = "http://wsPub/demandes/verifEmailResponse")
    public int verifEmail(
        @WebParam(name = "Email", targetNamespace = "")
        String email);

    /**
     * 
     * @param idc
     * @return
     *     returns java.util.List<wspub.Panier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectLivreC", targetNamespace = "http://wsPub/", className = "wspub.SelectLivreC")
    @ResponseWrapper(localName = "selectLivreCResponse", targetNamespace = "http://wsPub/", className = "wspub.SelectLivreCResponse")
    @Action(input = "http://wsPub/demandes/selectLivreCRequest", output = "http://wsPub/demandes/selectLivreCResponse")
    public List<Panier> selectLivreC(
        @WebParam(name = "idc", targetNamespace = "")
        int idc);

    /**
     * 
     * @param cb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifCB", targetNamespace = "http://wsPub/", className = "wspub.VerifCB")
    @ResponseWrapper(localName = "verifCBResponse", targetNamespace = "http://wsPub/", className = "wspub.VerifCBResponse")
    @Action(input = "http://wsPub/demandes/verifCBRequest", output = "http://wsPub/demandes/verifCBResponse")
    public boolean verifCB(
        @WebParam(name = "cb", targetNamespace = "")
        int cb);

}
